services:
  - type: web
    name: yt-api
    env: node
    buildCommand: |
      apt-get update && apt-get install -y curl
      curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp
      chmod a+rx /usr/local/bin/yt-dlp
      npm install
    startCommand: node server.js
